// <auto-generated />
using System;
using EvolutionOfCreatures.Db;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace EvolutionOfCreatures.Db.Migrations
{
    [DbContext(typeof(EvolutionOfCreaturesContext))]
    partial class EvolutionOfCreaturesContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.9")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("EvolutionOfCreatures.Db.Entities.Account", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("TransactionIds")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Accounts");
                });

            modelBuilder.Entity("EvolutionOfCreatures.Db.Entities.Player", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AccountId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("Rating")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AccountId")
                        .IsUnique();

                    b.ToTable("Players");
                });

            modelBuilder.Entity("EvolutionOfCreatures.Db.Entities.PlayerProgress", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("MaxLevel")
                        .HasColumnType("int");

                    b.Property<Guid>("PlayerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Version")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PlayerId")
                        .IsUnique();

                    b.ToTable("PlayersProgress");
                });

            modelBuilder.Entity("EvolutionOfCreatures.Db.Entities.PlayerSettings", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("LogLevel")
                        .HasColumnType("int");

                    b.Property<Guid>("PlayerId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("PlayerId")
                        .IsUnique();

                    b.ToTable("PlayerSettings");
                });

            modelBuilder.Entity("EvolutionOfCreatures.Db.Entities.PlayerStatistics", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("OfflineGameCount")
                        .HasColumnType("int");

                    b.Property<int>("OfflineWinCount")
                        .HasColumnType("int");

                    b.Property<int>("OnlineGameCount")
                        .HasColumnType("int");

                    b.Property<int>("OnlineWinCount")
                        .HasColumnType("int");

                    b.Property<Guid>("PlayerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Version")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PlayerId")
                        .IsUnique();

                    b.ToTable("PlayersStatistics");
                });

            modelBuilder.Entity("EvolutionOfCreatures.Db.Entities.Player", b =>
                {
                    b.HasOne("EvolutionOfCreatures.Db.Entities.Account", null)
                        .WithOne("Player")
                        .HasForeignKey("EvolutionOfCreatures.Db.Entities.Player", "AccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("EvolutionOfCreatures.Db.Entities.PlayerProgress", b =>
                {
                    b.HasOne("EvolutionOfCreatures.Db.Entities.Player", null)
                        .WithOne("PlayerProgress")
                        .HasForeignKey("EvolutionOfCreatures.Db.Entities.PlayerProgress", "PlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("EvolutionOfCreatures.Db.Entities.PlayerSettings", b =>
                {
                    b.HasOne("EvolutionOfCreatures.Db.Entities.Player", null)
                        .WithOne("PlayerSettings")
                        .HasForeignKey("EvolutionOfCreatures.Db.Entities.PlayerSettings", "PlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("EvolutionOfCreatures.Db.Entities.PlayerStatistics", b =>
                {
                    b.HasOne("EvolutionOfCreatures.Db.Entities.Player", null)
                        .WithOne("PlayerStatistics")
                        .HasForeignKey("EvolutionOfCreatures.Db.Entities.PlayerStatistics", "PlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("EvolutionOfCreatures.Db.Entities.Account", b =>
                {
                    b.Navigation("Player");
                });

            modelBuilder.Entity("EvolutionOfCreatures.Db.Entities.Player", b =>
                {
                    b.Navigation("PlayerProgress");

                    b.Navigation("PlayerSettings");

                    b.Navigation("PlayerStatistics");
                });
#pragma warning restore 612, 618
        }
    }
}
